modLoader="javafml"
loaderVersion="[42,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/InfusedFoods/issues"

[[mods]]
	modId="infusedfoods"
	version="${file.jarVersion}"
	displayName="InfusedFoods"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/infusedfoods.json"
	displayURL="https://www.apexstudios.dev/infused-foods"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Add the ability to apply potion effects to foods."

[[dependencies.infusedfoods]]
	modId="forge"
	mandatory=true
	versionRange="[42.0.2,43.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.1,1.20)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="commonality"
	mandatory=true
	versionRange="[3.0.0,4.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="apexcore"
	mandatory=true
	embedded=true
	versionRange="[6.0.0,7.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.infusedfoods]]
	modId="jei"
	mandatory=false
	versionRange="[11.2.0.241,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		curseforge="jei"