modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/InfusedFoods/issues"

[[mods]]
	modId="infusedfoods"
	version="${file.jarVersion}"
	displayName="InfusedFoods"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/infusedfoods.json"
	displayURL="https://www.apexstudios.dev/infused-foods"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Artist"
	authors="ApexStudios"
	description="Infuse edible foods with any Potion Effect"

[[dependencies.infusedfoods]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="apexcore"
	mandatory=false
	versionRange="[4.11.1,5.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.infusedfoods]]
	modId="commonality"
	mandatory=true
	versionRange="[1.3.0,2.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		ignore=true
[[dependencies.infusedfoods]]
	modId="jei"
	mandatory=false
	versionRange="[9.7.1.+,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.infusedfoods.custom.mc-publish]
		curseforge="jei"