modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/InfusedFoods/issues"

[[mods]]
	modId="infusedfoods"
	version="${file.jarVersion}"
	displayName="InfusedFoods"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/infusedfoods.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/infused-foods"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Add the ability to apply potion effects to foods."

[[dependencies.infusedfoods]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="apexcore"
	mandatory=true
	versionRange="[1.18.2,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="jei"
	mandatory=false
	versionRange="[10.1.3.+,)"
	ordering="AFTER"
	side="BOTH"